name: unit-tests
on:
  pull_request:
    branches:
      - 'dev*'
      - 'releases/v*'
  push:
    branches:
      - 'dev*'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.4.1

